language: python

env:
  - TOXENV=pep8
  - TOXENV=py3pep8
  - TOXENV=docs
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

install: .travis/install.sh

script: .travis/run.sh
